project:
  type: website
  output-dir: docs

website:
  title: "Tynshana Boone"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - research.qmd
      - cv.qmd
      - text: Assignments
        menu:
          - href: assign01.qmd
            text: Assignment 1
          - href: assign02.qmd
            text: Assignment 2
          - href: assign03.qmd
            text: Assignment 3

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto

editor: visual
