{
  "hash": "36da3113253a37de6678223ba463e9af",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Assignment 4: Webscraping 1\"\nexecute:\n  message: false\n  warning: false\nformat:\n  html:\n    code-fold: true\n    code-summary: \"Show code\"\n---\n\nThis page scrapes a practice site and two Wikipedia tables with rvest, cleans the foreign-exchange reserves table, and compares it with the same numbers from the World Bank API. It ends with a one-page plan for collecting web data for my own research. Answers are labeled with the question numbers from the assignment.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(rvest)\nlibrary(dplyr)\nlibrary(stringr)\nlibrary(readr)\nlibrary(purrr)\nlibrary(ggplot2)\nlibrary(knitr)\n\noptions(HTTPUserAgent = \"EPPS 6302 class assignment (UT Dallas)\")\n\n# save each page once, then read the saved copy\ndir <- \"data/webscrape\"\ndir.create(dir, showWarnings = FALSE, recursive = TRUE)\n\nfetch <- function(url, file) {\n  path <- file.path(dir, file)\n  if (!file.exists(path)) {\n    stopifnot(robotstxt::paths_allowed(url))   # check robots.txt first\n    download.file(url, path, quiet = TRUE)\n    Sys.sleep(2)                               # pause between requests\n  }\n  read_html(path)\n}\n\nbooks_urls <- paste0(\"https://books.toscrape.com/catalogue/page-\", 1:5, \".html\")\nwiki_url   <- \"https://en.wikipedia.org/wiki/List_of_countries_by_foreign-exchange_reserves\"\ncoffee_url <- \"https://en.wikipedia.org/wiki/List_of_countries_by_coffee_production\"\n```\n:::\n\n\n## 0. Permission\n\nI checked each path with `robotstxt::paths_allowed()` before the first request. `fetch()` also runs this check before every download.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nallowed <- tibble(\n  url = c(books_urls[1], wiki_url, coffee_url),\n  allowed = map_lgl(url, \\(u) suppressWarnings(robotstxt::paths_allowed(u)))\n)\nkable(allowed)\n```\n\n::: {.cell-output-display}\n\n\n|url                                                                          |allowed |\n|:----------------------------------------------------------------------------|:-------|\n|https://books.toscrape.com/catalogue/page-1.html                             |TRUE    |\n|https://en.wikipedia.org/wiki/List_of_countries_by_foreign-exchange_reserves |TRUE    |\n|https://en.wikipedia.org/wiki/List_of_countries_by_coffee_production         |TRUE    |\n\n\n:::\n:::\n\n\nAll three are allowed. Wikipedia's robots.txt blocks some crawlers and internal pages, but not articles. books.toscrape.com has no robots.txt (it returns 404), so nothing is restricted, and the site was built for scraping practice.\n\n## 1. Warm up on books.toscrape.com\n\n### 1a. First page\n\nThis is the first block of `rvest_wiki01.R`: title, price and rating for the 20 books on page 1. The only change is that the page is read through `fetch()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbooks_pg <- fetch(books_urls[1], \"books_page-1.html\")\n\nbooks <- tibble(\n  title  = books_pg |> html_elements(\"article.product_pod h3 a\") |> html_attr(\"title\"),\n  price  = books_pg |> html_elements(\"article.product_pod p.price_color\") |> html_text2(),\n  rating = books_pg |> html_elements(\"article.product_pod p.star-rating\") |>\n             html_attr(\"class\") |> str_remove(\"star-rating \")\n) |>\n  mutate(price_gbp = parse_number(price))\n\nkable(head(books))\n```\n\n::: {.cell-output-display}\n\n\n|title                                 |price  |rating | price_gbp|\n|:-------------------------------------|:------|:------|---------:|\n|A Light in the Attic                  |£51.77 |Three  |     51.77|\n|Tipping the Velvet                    |£53.74 |One    |     53.74|\n|Soumission                            |£50.10 |One    |     50.10|\n|Sharp Objects                         |£47.82 |Four   |     47.82|\n|Sapiens: A Brief History of Humankind |£54.23 |Five   |     54.23|\n|The Requiem Red                       |£22.65 |One    |     22.65|\n\n\n:::\n:::\n\n\n### 1b. Five pages in one dataframe\n\nThe same selectors in a function, run on pages 1 to 5 and bound into one dataframe. Ratings are changed from words to numbers.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nscrape_books <- function(i) {\n  pg <- fetch(books_urls[i], paste0(\"books_page-\", i, \".html\"))\n  tibble(\n    page   = i,\n    title  = pg |> html_elements(\"article.product_pod h3 a\") |> html_attr(\"title\"),\n    price  = pg |> html_elements(\"article.product_pod p.price_color\") |> html_text2() |> parse_number(),\n    rating = pg |> html_elements(\"article.product_pod p.star-rating\") |>\n               html_attr(\"class\") |> str_remove(\"star-rating \")\n  )\n}\n\nbooks5 <- map(1:5, scrape_books) |>\n  list_rbind() |>\n  mutate(rating = match(rating, c(\"One\", \"Two\", \"Three\", \"Four\", \"Five\")))\n\nbooks5 |> count(page, name = \"books\") |> kable()\n```\n\n::: {.cell-output-display}\n\n\n| page| books|\n|----:|-----:|\n|    1|    20|\n|    2|    20|\n|    3|    20|\n|    4|    20|\n|    5|    20|\n\n\n:::\n:::\n\n\nThat gives 100 books across 5 pages, with prices from £10.16 to £58.11 and a mean rating of 2.93 stars.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkable(head(books5, 10))\n```\n\n::: {.cell-output-display}\n\n\n| page|title                                                                                          | price| rating|\n|----:|:----------------------------------------------------------------------------------------------|-----:|------:|\n|    1|A Light in the Attic                                                                           | 51.77|      3|\n|    1|Tipping the Velvet                                                                             | 53.74|      1|\n|    1|Soumission                                                                                     | 50.10|      1|\n|    1|Sharp Objects                                                                                  | 47.82|      4|\n|    1|Sapiens: A Brief History of Humankind                                                          | 54.23|      5|\n|    1|The Requiem Red                                                                                | 22.65|      1|\n|    1|The Dirty Little Secrets of Getting Your Dream Job                                             | 33.34|      4|\n|    1|The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull        | 17.93|      3|\n|    1|The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics | 22.60|      4|\n|    1|The Black Maria                                                                                | 52.15|      1|\n\n\n:::\n:::\n\n\n## 2. The Wikipedia table\n\n### 2a. Foreign-exchange reserves\n\nThe page has 2 tables with the `wikitable` class: the reserves list (about 200 rows) and a quarterly currency breakdown. In the reserves table, the first two rows are not countries. The header takes up three rows, and `html_table()` only uses the first as column names.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwiki_pg <- fetch(wiki_url, \"wiki_fx_reserves.html\")\ntabs <- wiki_pg |> html_elements(\"table.wikitable\")\n\n# look at every table before picking one\ntabs |> html_table() |> map(dim) |> map_dfr(\\(d) tibble(rows = d[1], columns = d[2])) |>\n  mutate(table = row_number(), .before = 1) |> kable()\n```\n\n::: {.cell-output-display}\n\n\n| table| rows| columns|\n|-----:|----:|-------:|\n|     1|  198|       8|\n|     2|   28|      13|\n\n\n:::\n\n```{.r .cell-code}\nreserves_raw <- tabs[[1]] |> html_table()\nkable(head(reserves_raw, 4))\n```\n\n::: {.cell-output-display}\n\n\n|Country(as recognized by the UN) |Continent |Foreign exchange reserves |Foreign exchange reserves |Foreign exchange reserves |Foreign exchange reserves |Last reporteddate |Ref. |\n|:--------------------------------|:---------|:-------------------------|:-------------------------|:-------------------------|:-------------------------|:-----------------|:----|\n|Country(as recognized by the UN) |Continent |Including gold            |Including gold            |Excluding gold            |Excluding gold            |Last reporteddate |Ref. |\n|Country(as recognized by the UN) |Continent |US$ million               |Change                    |US$ million               |Change                    |Last reporteddate |Ref. |\n|China                            |Asia      |3,854,885                 |4,299                     |3,504,805                 |115,499                   |1 August 2026     |[3]  |\n|Japan                            |Asia      |1,287,470                 |18,400                    |1,259,248                 |16,230                    |30 June 2026      |[4]  |\n\n\n:::\n:::\n\n\n### 2b. A different table: coffee production\n\nI pointed the program at the [list of countries by coffee production](https://en.wikipedia.org/wiki/List_of_countries_by_coffee_production), since coffee is my research topic. Here is the clean-up step from `rvest_wiki01.R`, unchanged, run on both pages:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nscript_clean <- function(raw) {\n  raw |>\n    janitor::clean_names() |>\n    mutate(across(where(is.character),\n                  ~ .x |> str_remove_all(\"\\\\[.*?\\\\]\") |> str_squish())) |>\n    filter(!str_detect(country_or_region, regex(\"total|world\", ignore_case = TRUE)))\n}\n\ncoffee_raw <- fetch(coffee_url, \"wiki_coffee_production.html\") |>\n  html_elements(\"table.wikitable\") |> pluck(1) |> html_table()\n\nscript_clean(reserves_raw)\n```\n\n::: {.cell-output .cell-output-error}\n\n```\nError in `filter()`:\nℹ In argument: `!str_detect(country_or_region, regex(\"total|world\",\n  ignore_case = TRUE))`.\nCaused by error:\n! object 'country_or_region' not found\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"false\"}\nscript_clean(coffee_raw)\n```\n\n::: {.cell-output .cell-output-error}\n\n```\nError in `filter()`:\nℹ In argument: `!str_detect(country_or_region, regex(\"total|world\",\n  ignore_case = TRUE))`.\nCaused by error:\n! object 'country_or_region' not found\n```\n\n\n:::\n:::\n\n\nWhat broke:\n\n- **The column name.** The filter uses `country_or_region`. The reserves table now calls that column \"Country (as recognized by the UN)\" and the coffee table calls it \"Country\", so the code fails on both pages. Any header edit on Wikipedia breaks the script.\n- **The table layout.** My reserves cleaning in 2c names eight columns. The coffee table has two (country and tonnes), so that code fails on it too. Each table needs its own cleaning.\n- **The World row.** The coffee table starts with a World total, so the Total/World filter matters here. On the reserves page it removes nothing.\n- **What did not break:** `tabs[[1]]` was the right table on both pages. That was luck, since the code takes the first table without checking.\n\nThe coffee table cleaned for its own layout (FAO production for 2023, per the table caption):\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncoffee <- coffee_raw |>\n  rename(country = 1, tonnes = 2) |>\n  mutate(country = str_remove_all(country, \"\\\\[.*?\\\\]|[*α]\") |> str_squish(),\n         tonnes  = parse_number(tonnes)) |>\n  filter(!str_detect(country, regex(\"^(total|world)$\", ignore_case = TRUE)))\n\ncoffee |> slice_head(n = 10) |> kable(format.args = list(big.mark = \",\"))\n```\n\n::: {.cell-output-display}\n\n\n|country                  |    tonnes|\n|:------------------------|---------:|\n|Brazil                   | 3,405,267|\n|Vietnam                  | 1,956,782|\n|Indonesia                |   760,192|\n|Colombia                 |   680,858|\n|Ethiopia                 |   559,400|\n|Honduras                 |   384,361|\n|Uganda                   |   384,000|\n|Peru                     |   369,551|\n|India                    |   332,848|\n|Central African Republic |   316,108|\n\n\n:::\n:::\n\n\nThat leaves 37 producing countries after the World row is removed.\n\n### 2c. Cleaning the reserves table\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nclean_text <- function(x) {\n  x |>\n    str_replace_all(\"[\\u2009\\u202f\\u00a0]\", \" \") |>   # thin and non-breaking spaces\n    str_remove_all(\"\\\\[.*?\\\\]\") |>                 # footnote markers like [1] or [note 2]\n    str_remove_all(\"\\\\*\") |>                       # the * the page adds after some names\n    str_squish()\n}\n\nreserves <- reserves_raw |>\n  # (ii) header spans three rows: set names, drop the two extra rows\n  set_names(c(\"country\", \"continent\", \"incl_gold_musd\", \"incl_gold_change\",\n              \"excl_gold_musd\", \"excl_gold_change\", \"last_reported\", \"ref\")) |>\n  filter(!country %in% names(reserves_raw)) |>\n  mutate(across(everything(), clean_text)) |>\n  # (ii) any Total or World row\n  filter(!str_detect(country, regex(\"total|world\", ignore_case = TRUE))) |>\n  # (ii) drop the ref and change columns\n  select(-ref, -incl_gold_change, -excl_gold_change) |>\n  mutate(across(ends_with(\"_musd\"), parse_number),\n         # (i) dates come in several formats: \"1 Mar 2024\", \"11 Sept 2026\", \"12 JUN 2026\"\n         date_text = last_reported,\n         last_reported = lubridate::dmy(str_replace(last_reported, \"\\\\bSept\\\\b\", \"Sep\"), quiet = TRUE))\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncheck <- tibble(\n  step = c(\"Rows from html_table()\", \"Header rows dropped\", \"Total or World rows dropped\",\n           \"Country rows left\", \"Footnote markers [n] found in cells\",\n           \"Thin or non-breaking spaces found in cells\", \"Dates that did not parse\"),\n  n = c(nrow(reserves_raw),\n        sum(reserves_raw[[1]] %in% names(reserves_raw)),\n        sum(str_detect(clean_text(reserves_raw[[1]]), regex(\"total|world\", ignore_case = TRUE))),\n        nrow(reserves),\n        sum(str_detect(unlist(reserves_raw[, 1:7]), \"\\\\[.*?\\\\]\")),\n        sum(str_detect(unlist(reserves_raw[, 1:7]), \"[\\u2009\\u202f\\u00a0]\")),\n        sum(is.na(reserves$last_reported)))\n)\nkable(check)\n```\n\n::: {.cell-output-display}\n\n\n|step                                       |   n|\n|:------------------------------------------|---:|\n|Rows from html_table()                     | 198|\n|Header rows dropped                        |   2|\n|Total or World rows dropped                |   0|\n|Country rows left                          | 196|\n|Footnote markers [n] found in cells        |   0|\n|Thin or non-breaking spaces found in cells |   0|\n|Dates that did not parse                   |   1|\n\n\n:::\n:::\n\n\nThis version of the page has no footnote markers or thin spaces in the cells, and no Total or World row. Footnotes now sit in their own Ref. column, which I dropped. I kept the filters anyway, since a later edit could bring these back.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbad_dates <- reserves |> filter(is.na(last_reported)) |> select(country, date_text)\nkable(bad_dates)\n```\n\n::: {.cell-output-display}\n\n\n|country |date_text   |\n|:-------|:-----------|\n|Albania |31 Apr 2024 |\n\n\n:::\n:::\n\n\nThe date that would not parse is \"31 Apr 2024\" for Albania, which is not a real date since April has 30 days. I left it missing rather than guess what the editor meant.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreserves |>\n  count(year = lubridate::year(last_reported), name = \"countries\") |>\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n| year| countries|\n|----:|---------:|\n| 2024|       168|\n| 2025|         6|\n| 2026|        21|\n|   NA|         1|\n\n\n:::\n:::\n\n\nThe \"excluding gold\" column is blank for 154 of the 196 countries, because Wikipedia shows \"N/a\" there. So I use \"including gold\", which is filled in for every country and is also what the World Bank reports.\n\nThe \"last reported\" dates run from March 2024 to September 2026, so the table compares countries at different points in time.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreserves |> select(-date_text) |> slice_head(n = 10) |>\n  kable(format.args = list(big.mark = \",\"))\n```\n\n::: {.cell-output-display}\n\n\n|country      |continent   | incl_gold_musd| excl_gold_musd|last_reported |\n|:------------|:-----------|--------------:|--------------:|:-------------|\n|China        |Asia        |      3,854,885|      3,504,805|2026-08-01    |\n|Japan        |Asia        |      1,287,470|      1,259,248|2026-06-30    |\n|Switzerland  |Europe      |        939,140|        932,282|2026-06-30    |\n|India        |Asia        |        785,710|        671,900|2026-09-04    |\n|Russia       |Europe/Asia |        761,200|        434,487|2026-08-21    |\n|Taiwan       |Asia        |        597,150|        544,300|2026-06-30    |\n|Saudi Arabia |Asia        |        487,370|        494,482|2026-05-31    |\n|Hong Kong    |Asia        |        445,900|        441,788|2026-06-30    |\n|South Korea  |Asia        |        427,400|        423,100|2026-06-30    |\n|Singapore    |Asia        |        426,830|        419,329|2026-06-30    |\n\n\n:::\n\n```{.r .cell-code}\nwrite_csv(reserves, file.path(dir, \"reserves_wiki_clean.csv\"))\n```\n:::\n\n\n## 3. The same quantity from the World Bank\n\n### 3a. One call\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nwdi_file <- file.path(dir, \"wdi_FI.RES.TOTL.CD.rds\")\nif (!file.exists(wdi_file)) {\n  reserves_api <- WDI::WDI(indicator = \"FI.RES.TOTL.CD\", start = 2015, end = 2025, extra = TRUE)\n  saveRDS(reserves_api, wdi_file)\n}\nreserves_api <- readRDS(wdi_file)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# countries only, latest year with data\nwb <- reserves_api |>\n  filter(region != \"Aggregates\", !is.na(FI.RES.TOTL.CD)) |>\n  group_by(iso3c) |>\n  slice_max(year, n = 1) |>\n  ungroup() |>\n  transmute(iso3c, wb_country = country, wb_year = year,\n            wb_musd = FI.RES.TOTL.CD / 1e6, lastupdated)\n\nwb |> count(wb_year, name = \"countries\") |> kable()\n```\n\n::: {.cell-output-display}\n\n\n| wb_year| countries|\n|-------:|---------:|\n|    2017|         2|\n|    2018|         1|\n|    2019|         1|\n|    2020|         2|\n|    2021|         2|\n|    2022|         1|\n|    2023|         4|\n|    2024|        40|\n|    2025|       124|\n\n\n:::\n:::\n\n\nThe World Bank series was last updated on 2026-07-13. Its latest year is 2025, and each value is the amount held at the end of that year.\n\n### 3b. Comparing the two\n\nCountry names differ between the two sources (\"Russia\" and \"Russian Federation\", \"South Korea\" and \"Korea, Rep.\"), so I matched them by country code, using the World Bank's country list and a short list of names it spells differently.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwb_names <- reserves_api |> distinct(country, iso3c) |> filter(iso3c != \"\")\nfix <- c(\"Russia\" = \"RUS\", \"South Korea\" = \"KOR\", \"Turkey\" = \"TUR\", \"Iran\" = \"IRN\",\n         \"Egypt\" = \"EGY\", \"Venezuela\" = \"VEN\", \"Vietnam\" = \"VNM\", \"Syria\" = \"SYR\",\n         \"Laos\" = \"LAO\", \"Slovakia\" = \"SVK\", \"Kyrgyzstan\" = \"KGZ\", \"Yemen\" = \"YEM\",\n         \"Gambia\" = \"GMB\", \"The Gambia\" = \"GMB\", \"Bahamas\" = \"BHS\", \"The Bahamas\" = \"BHS\",\n         \"Hong Kong\" = \"HKG\", \"Macau\" = \"MAC\", \"Macao\" = \"MAC\", \"Brunei\" = \"BRN\",\n         \"Czech Republic\" = \"CZE\", \"Czechia\" = \"CZE\", \"Ivory Coast\" = \"CIV\",\n         \"Cape Verde\" = \"CPV\", \"Republic of the Congo\" = \"COG\",\n         \"Democratic Republic of the Congo\" = \"COD\", \"DR Congo\" = \"COD\",\n         \"North Korea\" = \"PRK\", \"Micronesia\" = \"FSM\", \"Federated States of Micronesia\" = \"FSM\", \"Saint Lucia\" = \"LCA\",\n         \"Saint Kitts and Nevis\" = \"KNA\", \"Saint Vincent and the Grenadines\" = \"VCT\",\n         \"Palestine\" = \"PSE\", \"State of Palestine\" = \"PSE\", \"Kosovo\" = \"XKX\",\n         \"Curaçao\" = \"CUW\", \"East Timor\" = \"TLS\", \"Timor-Leste\" = \"TLS\",\n         \"São Tomé and Príncipe\" = \"STP\", \"Sao Tome and Principe\" = \"STP\",\n         \"Eswatini\" = \"SWZ\", \"Turkmenistan\" = \"TKM\", \"Somalia\" = \"SOM\")\n\ncompare <- reserves |>\n  mutate(iso3c = coalesce(unname(fix[country]), wb_names$iso3c[match(country, wb_names$country)])) |>\n  full_join(wb, by = \"iso3c\") |>\n  mutate(diff_pct = 100 * (incl_gold_musd - wb_musd) / wb_musd)\n\nonly_wiki <- compare |> filter(is.na(wb_musd), !is.na(incl_gold_musd))\nonly_wb   <- compare |> filter(is.na(incl_gold_musd), !is.na(wb_musd))\nboth      <- compare |> filter(!is.na(incl_gold_musd), !is.na(wb_musd))\n```\n:::\n\n\n176 countries are in both sources. 20 are only on Wikipedia and 1 is only in the World Bank data. For the World Bank I used each country's latest year with data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(both, aes(wb_musd / 1e3, incl_gold_musd / 1e3)) +\n  geom_abline(linetype = \"dashed\", colour = \"grey50\") +\n  geom_point(alpha = 0.6) +\n  scale_x_log10(labels = scales::comma) +\n  scale_y_log10(labels = scales::comma) +\n  labs(x = \"World Bank, latest year (US$ billion, log scale)\",\n       y = \"Wikipedia, including gold (US$ billion, log scale)\",\n       title = \"Reserves: Wikipedia vs World Bank\",\n       subtitle = \"Dashed line = same value in both\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](assign04_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nagree <- both |> summarise(within5 = mean(abs(diff_pct) <= 5), within20 = mean(abs(diff_pct) <= 20))\n```\n:::\n\n\nOnly 15% of the matched countries are within 5% of each other, and 41% are within 20%. The largest gaps:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nboth |>\n  arrange(desc(abs(diff_pct))) |>\n  slice_head(n = 12) |>\n  transmute(country, wikipedia_musd = incl_gold_musd, wiki_date = date_text,\n            world_bank_musd = round(wb_musd), wb_year = as.character(wb_year),\n            diff_pct = round(diff_pct, 1)) |>\n  kable(format.args = list(big.mark = \",\"))\n```\n\n::: {.cell-output-display}\n\n\n|country                          | wikipedia_musd|wiki_date   | world_bank_musd|wb_year | diff_pct|\n|:--------------------------------|--------------:|:-----------|---------------:|:-------|--------:|\n|South Sudan                      |             80|2 Mar 2024  |              16|2024    |    401.2|\n|São Tomé and Príncipe            |            186|1 Mar 2024  |              59|2024    |    216.4|\n|Bolivia                          |          1,769|1 Mar 2024  |             580|2025    |    205.0|\n|Gabon                            |          1,377|1 Mar 2024  |             639|2024    |    115.6|\n|North Macedonia                  |              4|31 Aug 2025 |           5,804|2025    |    -99.9|\n|Mozambique                       |              4|31 Jul 2025 |           3,843|2024    |    -99.9|\n|Equatorial Guinea                |             46|1 Mar 2024  |           1,077|2024    |    -95.7|\n|Afghanistan                      |            443|1 Oct 2024  |           9,749|2020    |    -95.5|\n|Chad                             |            143|1 Mar 2024  |           1,548|2024    |    -90.8|\n|Democratic Republic of the Congo |            505|14 Mar 2024 |           5,104|2023    |    -90.1|\n|Greece                           |          3,926|1 Mar 2024  |          24,048|2025    |    -83.7|\n|United States                    |        253,767|22 Aug 2025 |       1,385,447|2025    |    -81.7|\n\n\n:::\n:::\n\n\nThe ten largest holders:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nboth |>\n  slice_max(incl_gold_musd, n = 10) |>\n  transmute(country, wikipedia_musd = incl_gold_musd, wiki_date = date_text,\n            world_bank_musd = round(wb_musd), wb_year = as.character(wb_year), diff_pct = round(diff_pct, 1)) |>\n  kable(format.args = list(big.mark = \",\"))\n```\n\n::: {.cell-output-display}\n\n\n|country      | wikipedia_musd|wiki_date         | world_bank_musd|wb_year | diff_pct|\n|:------------|--------------:|:-----------------|---------------:|:-------|--------:|\n|China        |      3,854,885|1 August 2026     |       3,748,745|2025    |      2.8|\n|Japan        |      1,287,470|30 June 2026      |       1,371,402|2025    |     -6.1|\n|Switzerland  |        939,140|30 June 2026      |       1,075,680|2025    |    -12.7|\n|India        |        785,710|04 September 2026 |         700,074|2025    |     12.2|\n|Russia       |        761,200|21 August 2026    |         608,361|2024    |     25.1|\n|Saudi Arabia |        487,370|31 May 2026       |         505,164|2025    |     -3.5|\n|Hong Kong    |        445,900|30 June 2026      |         425,554|2023    |      4.8|\n|South Korea  |        427,400|30 June 2026      |         436,573|2025    |     -2.1|\n|Singapore    |        426,830|30 June 2026      |         432,114|2025    |     -1.2|\n|Brazil       |        366,913|30 Apr 2026       |         358,513|2025    |      2.3|\n\n\n:::\n:::\n\n\nOnly on Wikipedia:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nonly_wiki |> select(country, incl_gold_musd, date_text) |> kable(format.args = list(big.mark = \",\"))\n```\n\n::: {.cell-output-display}\n\n\n|country       | incl_gold_musd|date_text    |\n|:-------------|--------------:|:------------|\n|Taiwan        |        597,150|30 June 2026 |\n|Iran          |         24,300|1 Mar 2024   |\n|Turkmenistan  |         20,600|1 Mar 2024   |\n|Ivory Coast   |          9,800|1 Mar 2024   |\n|North Korea   |          9,109|1 Mar 2024   |\n|Vatican City  |          4,339|1 Mar 2024   |\n|Andorra       |          3,689|20 Mar 2024  |\n|Cuba          |          2,500|15 Mar 2024  |\n|Curaçao       |          1,080|20 Mar 2024  |\n|Niger         |          1,053|1 Mar 2024   |\n|Mali          |            604|1 Mar 2024   |\n|Syria         |            401|1 Mar 2024   |\n|Guinea-Bissau |            329|1 Mar 2024   |\n|Togo          |            208|1 Mar 2024   |\n|Senegal       |            164|1 Mar 2024   |\n|Benin         |             69|1 Mar 2024   |\n|Montserrat    |             54|1 Mar 2024   |\n|Burkina Faso  |             42|1 Mar 2024   |\n|Somalia       |             37|1 Mar 2024   |\n|Kiribati      |              8|1 Mar 2024   |\n\n\n:::\n:::\n\n\n**Which differ, and why.** The largest holders mostly agree (China, South Korea, Singapore, Brazil and Saudi Arabia are within 4%), but many smaller countries do not. The gaps have five causes:\n\n1. **Different dates.** 149 of the 196 Wikipedia rows have not been updated since March 2024, while the World Bank value is mostly for the end of 2025. For Bolivia, Gabon and South Sudan, the Wikipedia numbers are close to their World Bank values for 2023, but their reserves fell sharply after that. Some World Bank series also stop early (Hong Kong after 2023, Afghanistan after 2020).\n2. **Gold valuation.** The United States is 82% lower on Wikipedia. Its \"including gold\" figure is only about US$11 billion above \"excluding gold\", which is US gold valued at the old official price of $42.22 an ounce. The World Bank uses the market price, which adds over US$1 trillion.\n3. **Coverage.** The World Bank does not report Taiwan separately. Benin, Burkina Faso, Ivory Coast, Guinea-Bissau, Mali, Niger, Senegal and Togo share one central bank (the BCEAO), which holds their reserves together, so there is no World Bank figure for each country. Iran, North Korea, Cuba, Syria, Turkmenistan, Somalia, Andorra, Curaçao and Kiribati have no World Bank value for these years, and Vatican City and Montserrat are not in the World Bank's country list.\n4. **Units.** Mozambique and North Macedonia show 4 (US$ million) on Wikipedia but several billion at the World Bank. That looks like a number in billions entered in the millions column.\n5. **No checks.** Nothing on Wikipedia checks the entries. \"31 Apr 2024\" and the unit errors are the mistakes visible here, and there is no way to tell how many others there are.\n\n**Which vintage.** The World Bank numbers are end-of-year values, mostly for 2025, from the release updated on 2026-07-13. The Wikipedia numbers are from the page as I downloaded it on October 5, 2026, with reporting dates from March 2024 to September 2026. Scraping the page again next month could give different numbers, with no record of what changed.\n\n### 3c. When is scraping the right tool?\n\nScraping is the right tool when the data is only published on a web page, with no API or download, and the site's robots.txt and terms of service allow it. When the same numbers are available from an API or an official file, as the reserves are from the World Bank, use that instead, because it is documented, versioned and gives everyone the same answer.\n\n## 4. Data plan\n\nMy research looks at how the timing of my coffee intake relates to my daily focus, using my own coffee log and a writing-time tracker. Web data gives an outside comparison: when people in the US search for coffee, by hour and day of the week. This shows whether my pattern matches the general one.\n\n**a. Source.** Google Trends search interest for \"coffee\" in the US: hourly values for each 7-day window and daily values for the same three months as my logs. I chose it because it is the only free public source I found that shows coffee-related behavior by hour. The ICO and USDA publish coffee consumption only as yearly national totals, which cannot show a daily pattern. Coffee shop sales data would be closer to actual drinking, but it is not public.\n\n**b. robots.txt and Terms of Service.** The robots.txt for trends.google.com blocks `/explore?` and `/trends/api`, which are the pages a scraper would request, including the gtrendsR package I used in Assignment 2. Google's Terms of Service do not allow automated access that goes against robots.txt. So scraping Google Trends is not allowed, and I will not do it.\n\n**c. API.** Google opened an official Trends API in July 2025, but only for approved applicants, and it gives daily, weekly, monthly or yearly data, not hourly. I will apply and use it for the daily series if I am approved. For the hourly data, and until then, I will use the \"Download CSV\" button on the Trends website. That is a person using the site, not a bot, so it follows robots.txt and the terms. Since I am not scraping, no justification is needed.\n\n**d. Volume, rate limiting and caching.** About 13 hourly downloads (168 rows each) and one daily series over the three months, about 2,300 rows in total. Downloads are by hand, once a week, the same load as normal use. Google Trends returns a slightly different sample each time (Assignment 2 showed this), so I will save every file unchanged with the date in its name and log each download (search term, time window, download time). The analysis will only read the saved files.\n\n**e. What breaks, and how I will notice.** Google can change the CSV layout (header lines or column names), how small values are shown (currently \"<1\"), or how the sample is drawn. A script will check each new file before I use it: the expected column names, 168 rows for a 7-day hourly file, values between 0 and 100 with a top value of 100, and dates that match the window I asked for. If a check fails, the script stops and names the file.\n",
    "supporting": [
      "assign04_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}